"use client";

/**
 * MoneyDevKit Checkout Page
 * This page renders the MDK hosted checkout interface
 * 
 * How it works:
 * 1. User clicks "Pay with CashApp" button
 * 2. MDK creates a checkout session and navigates here
 * 3. This page displays the Lightning invoice QR code and payment options
 * 4. After payment, user is redirected to the success page
 * 
 * The [id] in the URL is the checkout session ID generated by MDK
 */

import { Checkout } from "@moneydevkit/nextjs";
import { use } from "react";

export default function CheckoutPage({ params }) {
  // Extract the checkout session ID from the URL parameters
  const { id } = use(params);

  // Render the MDK Checkout component
  // This component handles all payment UI including:
  // - Lightning invoice display
  // - QR code generation
  // - Payment status updates
  // - Redirect after successful payment
  return <Checkout id={id} />;
}

