/**
 * Checkout Page Component
 * 
 * This page displays the MoneyDevKit Lightning payment interface.
 * When a user clicks "Pay with Cash App" on an artwork page, they are
 * navigated to this checkout page with a unique session ID.
 * 
 * The <Checkout> component from MDK handles:
 * - Displaying the Lightning invoice QR code
 * - Showing payment status updates in real-time
 * - Automatically redirecting to success page after payment
 * - Handling payment timeouts and errors
 * 
 * The session ID in the URL ([id]) is automatically generated by
 * the useCheckout hook when navigate() is called.
 */
"use client";

import { Checkout } from "@moneydevkit/nextjs";
import { use } from "react";

export default function CheckoutPage({ params }: { params: Promise<{ id: string }> }) {
  // Unwrap the params promise to get the checkout session ID
  // In Next.js 15+, params is a promise that needs to be unwrapped
  const { id } = use(params);

  return (
    <div className="min-h-screen py-20 px-4">
      {/* 
        The Checkout component handles all payment UI and logic.
        It will automatically redirect to the success page after payment.
      */}
      <Checkout id={id} />
    </div>
  );
}

